try to avoid skipped test

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -6,7 +6,6 @@ on:
 
 jobs:
   build:
-    if: contains(github.event.pull_request.labels.*.name, 'run-tests')
     name: merge checks 
     runs-on: ubuntu-latest
     steps:
@@ -14,6 +13,12 @@ jobs:
     - uses: actions/setup-python@v3
       with:
         python-version: "3.12"
+
+    - name: Fail workflow until run
+      if: ${{ !contains(github.event.pull_request.labels.*.name, 'run-tests') }}
+      run: |
+        echo "Cannot merge until tests run"
+        exit 1
 
     - name: Build
       run: |
